(()=>{'use strict';
const map=window.paratyMap,L=window.L;if(!map||!L)return;
const $=id=>document.getElementById(id),key='paratygps-history-v1';let trips=[],active=null,overlay=null,startMarker=null,endMarker=null,current=null;
const valid=p=>p&&Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&Math.abs(p.lat)<=90&&Math.abs(p.lng)<=180;
try{const v=JSON.parse(localStorage.getItem(key));if(Array.isArray(v))trips=v.filter(t=>t&&Array.isArray(t.points)&&t.points.length>=2).map(t=>({...t,points:t.points.filter(valid)})).filter(t=>t.points.length>=2).slice(0,30)}catch{}
function nm(a,b){const r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlng=(b.lng-a.lng)*r,x=Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2;return 3440.065*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function segments(points){const out=[];for(const p of points){if(p.brk||!out.length)out.push([]);out[out.length-1].push(p)}return out}
function length(points){let d=0;for(const s of segments(points))for(let i=1;i<s.length;i++)d+=nm(s[i-1],s[i]);return d}
function persist(){let ok=true;try{localStorage.setItem(key,JSON.stringify(trips))}catch{ok=false;$('historyGuidance').textContent='Armazenamento do aparelho cheio. Exclua viagens antigas para salvar novas.'}render();return ok}
function icon(label){return L.divIcon({className:'',html:`<div class="route-point" style="width:28px;height:28px">${label}</div>`,iconSize:[28,28],iconAnchor:[14,14]})}
function clearOverlay(){if(overlay)overlay.remove();if(startMarker)startMarker.remove();if(endMarker)endMarker.remove();overlay=startMarker=endMarker=null}
function guidance(){if(!active)return;const t=trips.find(x=>x.id===active);if(!t){active=null;clearOverlay();$('historyGuidance').textContent='';return}if(!current){$('historyGuidance').textContent='Ative o GPS para comparar sua posição com a viagem anterior.';return}let nearest=Infinity;for(const p of t.points)nearest=Math.min(nearest,nm(current,p));const end=nm(current,t.points[t.points.length-1]);$('historyGuidance').textContent=`Distância aproximada até o traçado antigo: ${nearest.toFixed(2).replace('.',',')} MN. Até o destino antigo em linha reta: ${end.toFixed(2).replace('.',',')} MN. Isto não é orientação de rumo seguro.`}
function show(id){if(active===id){active=null;clearOverlay();$('historyGuidance').textContent='';render();return}const t=trips.find(x=>x.id===id);if(!t)return;clearOverlay();active=id;overlay=L.polyline(segments(t.points).map(s=>s.map(p=>[p.lat,p.lng])),{color:'#6934d6',weight:5,opacity:.8}).addTo(map);startMarker=L.marker([t.points[0].lat,t.points[0].lng],{icon:icon('A')}).addTo(map).bindPopup('Início da viagem gravada');const last=t.points[t.points.length-1];endMarker=L.marker([last.lat,last.lng],{icon:icon('B')}).addTo(map).bindPopup('Fim da viagem gravada');map.fitBounds(overlay.getBounds().pad(.15),{maxZoom:15});guidance();render()}
function download(t){const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&apos;','"':'&quot;'}[c]));const pts=segments(t.points).map(s=>'<trkseg>'+s.map(p=>`<trkpt lat="${p.lat}" lon="${p.lng}">${Number.isFinite(p.time)?`<time>${new Date(p.time).toISOString()}</time>`:''}</trkpt>`).join('')+'</trkseg>').join('');const xml=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="ParatyGPS" xmlns="http://www.topografix.com/GPX/1/1"><trk><name>${esc(t.name)}</name><desc>Histórico de GPS; não é rota segura validada.</desc>${pts}</trk></gpx>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([xml],{type:'application/gpx+xml'}));a.download='paraty-viagem-'+(Number.isFinite(t.created)?new Date(t.created).toISOString().slice(0,10):'sem-data')+'.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function render(){const list=$('historyList');list.replaceChildren();$('historyCount').textContent=`${trips.length} ${trips.length===1?'viagem':'viagens'}`;if(!trips.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='Nenhuma viagem salva. Ative o GPS e registre um percurso.';list.append(empty);return}for(const t of trips){const card=document.createElement('div');card.className='history-card'+(active===t.id?' active':'');const title=document.createElement('strong');title.textContent=t.name;const info=document.createElement('small');info.textContent=`${new Date(t.created).toLocaleString('pt-BR')} · ${length(t.points).toFixed(2).replace('.',',')} MN · ${t.points.length} posições`;const actions=document.createElement('div');actions.className='row';for(const [label,action] of [[active===t.id?'Ocultar':'Ver no mapa',()=>show(t.id)],['↓ GPX',()=>download(t)],['Excluir',()=>{if(!confirm(`Excluir a viagem “${t.name}”?`))return;if(active===t.id){active=null;clearOverlay();$('historyGuidance').textContent=''}trips=trips.filter(x=>x.id!==t.id);persist()}]]){const b=document.createElement('button');b.className='secondary';b.textContent=label;b.onclick=action;actions.append(b)}card.append(title,info,actions);list.append(card)}}
window.addEventListener('paraty-position',e=>{current=e.detail;guidance()});
window.addEventListener('paraty-voyage-finished',e=>{const points=e.detail.filter(valid);if(points.length<2){$('historyGuidance').textContent='Viagem curta demais para salvar: aguarde ao menos duas posições diferentes do GPS.';return}const name=prompt('Nome desta viagem:',`Viagem ${new Date().toLocaleDateString('pt-BR')}`);if(name===null){$('historyGuidance').textContent='Viagem não salva no histórico. O percurso atual continua no aparelho.';return}const prev=trips;trips=[{id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),name:name.trim().slice(0,60)||'Viagem sem nome',created:Date.now(),points},...trips];const dropped=trips.length>30;trips=trips.slice(0,30);if(!persist()){trips=prev;render();return}$('historyGuidance').textContent='Viagem salva. Use “Ver no mapa” para consultar o trajeto depois.'+(dropped?' A viagem mais antiga foi removida (limite de 30).':'')});render();
})();
