(()=>{'use strict';
const map=window.paratyMap, L=window.L;
if(!map||!L)return;
const el=id=>document.getElementById(id), key='paratygps-route-v1', prefKey='paratygps-route-prefs';
let route={start:null,end:null,via:[]},mode=null,drawn=[],routeLayers=[],computed=null,worker=null,ready=null,computeSeq=0,timer=0,shade=null;
try{const value=JSON.parse(localStorage.getItem(key));if(value&&typeof value==='object')route={start:valid(value.start),end:valid(value.end),via:Array.isArray(value.via)?value.via.map(valid).filter(Boolean).slice(0,50):[]}}catch{}
function valid(p){return p&&Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&Math.abs(p.lat)<=90&&Math.abs(p.lng)<=180?{lat:p.lat,lng:p.lng}:null}
const format=p=>`${Math.abs(p.lat).toFixed(5)}° ${p.lat<0?'S':'N'} · ${Math.abs(p.lng).toFixed(5)}° ${p.lng<0?'O':'L'}`,dec=(n,d=2)=>n.toFixed(d).replace('.',',');
function nauticalMiles(a,b){const r=Math.PI/180,dLat=(b.lat-a.lat)*r,dLon=(b.lng-a.lng)*r,v=Math.sin(dLat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dLon/2)**2;return 3440.065*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))}
// Index in route.via where p adds the least distance: between two neighbours, or at an open end of the route.
function bestSlot(p){const seq=[route.start,...route.via,route.end];let best=route.via.length,cost=Infinity;for(let k=0;k<=route.via.length;k++){const a=seq[k],b=seq[k+1],c=a&&b?nauticalMiles(a,p)+nauticalMiles(p,b)-nauticalMiles(a,b):a?nauticalMiles(a,p):b?nauticalMiles(p,b):0;if(c<cost){cost=c;best=k}}return best}
const pick=(id,allowed,def)=>{const v=Number(el(id).value);return allowed.includes(v)?v:def},margin=()=>pick('routeMargin',[30,50,100,200],50),depth=()=>pick('routeDepth',[2,5,10],2);
try{const p=JSON.parse(localStorage.getItem(prefKey))||{};if(p.margin)el('routeMargin').value=String(p.margin);if(p.depth)el('routeDepth').value=String(p.depth)}catch{}
function savePrefs(){try{localStorage.setItem(prefKey,JSON.stringify({margin:margin(),depth:depth()}))}catch{}}
function save(){try{localStorage.setItem(key,JSON.stringify(route))}catch{}render();schedule()}
function select(next){mode=mode===next?null:next;window.routeSelectionActive=Boolean(mode);for(const [id,type] of [['routeStart','start'],['routeEnd','end'],['routeVia','via']]){el(id).classList.toggle('selected',mode===type);el(id).setAttribute('aria-pressed',String(mode===type))}document.querySelector('.maptop span').textContent=mode?`Toque no mapa para ${mode==='via'?'inserir passagem':mode==='start'?'marcar origem':'marcar destino'}`:'Toque no mapa para selecionar um ponto'}
function icon(label,via){return L.divIcon({className:'',html:`<div class="route-point ${via?'route-via':''}" style="width:28px;height:28px">${label}</div>`,iconSize:[28,28],iconAnchor:[14,14]})}
function info(text,warn){const box=el('routeDistance');box.textContent=text;box.classList.toggle('route-alert',Boolean(warn))}
function render(){drawn.forEach(m=>m.remove());drawn=[];const list=el('routeList');list.replaceChildren();const entries=[['Origem',route.start,'start',0],...route.via.map((p,i)=>[`Passagem ${i+1}`,p,'via',i]),['Destino',route.end,'end',0]];
for(const [name,p,type,index] of entries){const row=document.createElement('div');row.className='route-item';const label=document.createElement('span');label.innerHTML=`<strong>${name}</strong><small>${p?format(p):'Ainda não definido'}</small>`;row.append(label);if(p){const btn=document.createElement('button');btn.className='iconbtn';btn.textContent='×';btn.setAttribute('aria-label',`Remover ${name}`);btn.onclick=()=>{if(type==='via')route.via.splice(index,1);else route[type]=null;save()};row.append(btn);const marker=L.marker([p.lat,p.lng],{icon:icon(type==='start'?'A':type==='end'?'B':String(index+1),type==='via'),draggable:true,zIndexOffset:600}).addTo(map).bindPopup(`${name}<br>${format(p)}<br>Arraste para ajustar`);marker.on('dragend',()=>{const point=marker.getLatLng(),value={lat:point.lat,lng:point.lng};if(type==='via')route.via[index]=value;else route[type]=value;save()});drawn.push(marker)}list.append(row)}}
function clearRoute(){routeLayers.forEach(l=>l.remove());routeLayers=[];computed=null}

// ---- Router worker with the navigation mask of DHN chart 1633 ----
function call(type,payload){if(!worker){worker=new Worker('./router.js');worker.pending=new Map();worker.seq=0;worker.onmessage=e=>{const p=worker.pending.get(e.data.id);if(p){worker.pending.delete(e.data.id);p(e.data.result)}};worker.onerror=()=>{for(const p of worker.pending.values())p({ok:false,reason:'error'});worker.pending.clear()}}const id=++worker.seq;return new Promise(res=>{worker.pending.set(id,res);worker.postMessage({type,id,...payload})})}
function loadChart(){if(!ready)ready=call('load',{url:new URL('./chart-mask.bin',location.href).href}).then(r=>{if(!r||r.ok===false){ready=null;el('chartStatus').textContent='Não foi possível carregar os dados da carta náutica. Recarregue o app com internet.';return false}el('chartStatus').textContent='Base: carta náutica DHN nº 1633 (Baía da Ilha Grande – Parte Oeste, 1:40.000, e Baía de Parati, 1:20.000). Funciona sem internet.';return true});return ready}

async function compute(){const seq=++computeSeq;clearRoute();if(!route.start||!route.end){info('Marque origem e destino no mapa para calcular a rota.');return}
if(typeof Worker==='undefined'){info('Este navegador não consegue calcular rotas.',true);return}
info('Calculando rota pela água…');if(!await loadChart()){if(seq===computeSeq)info('Rota não calculada: dados da carta indisponíveis.',true);return}if(seq!==computeSeq)return;
const pts=[route.start,...route.via,route.end],m=margin(),dp=depth(),r=await call('plan',{points:pts.map(p=>[p.lat,p.lng]),opt:{hard:m,depth:dp}});if(seq!==computeSeq)return;
const names=['Origem',...route.via.map((_,i)=>`Passagem ${i+1}`),'Destino'];
if(!r.ok){info(r.reason==='outside'?`${names[r.index]} está fora da área da carta 1633 (oeste da Baía da Ilha Grande e Baía de Paraty).`:r.reason==='no-water'?`${names[r.index]} está a mais de 1,5 km de água com ${dp} m e margem de ${m} m. Mova o ponto.`:r.reason==='no-path'?`Não há passagem com profundidade mínima de ${dp} m e afastamento de ${m} m entre esses pontos. Tente uma margem menor, outro calado ou mova os pontos.`:'Não foi possível calcular a rota.',true);return}
computed={...r,margin:m,depth:dp};routeLayers.push(L.polyline(r.coords,{color:'#1d1d1b',weight:7,opacity:.35,interactive:false}).addTo(map),L.polyline(r.coords,{color:'#ff9f43',weight:4,opacity:.95,interactive:false}).addTo(map));
const notes=[];r.access.forEach((a,k)=>{if(!a)return;routeLayers.push(L.polyline(a.coords,{color:'#ffe08a',weight:3,dashArray:'5 7',interactive:false}).addTo(map));const name=k===0?'Saída da origem':k===r.access.length-1?'Chegada ao destino':`Acesso à passagem ${k}`;if(a.onLand)notes.push(`${k===0?'A origem':k===r.access.length-1?'O destino':'A passagem '+k} está marcada em terra na carta.`);if(a.metres>=30)notes.push(a.viaWater?`${name}: ${a.metres} m em água rasa (menos de ${dp} m na carta, podendo secar na baixa-mar), tracejado amarelo — só com maré, embarcação adequada e atenção visual.`:`${name}: ${a.metres} m em linha reta sem verificação (ponto em terra ou isolado).`)});
info(`Rota sugerida: ${dec(r.nm)} MN · profundidade na carta ≥ ${r.minDepth} m em toda a rota · afastamento mínimo de terra, secos e rasos ≈ ${r.minClear} m.`+(notes.length?' '+notes.join(' '):''),notes.length>0)}
function schedule(){clearTimeout(timer);timer=setTimeout(compute,250)}

async function toggleShade(){if(shade){shade.remove();shade=null;el('routeShade').textContent='Mostrar áreas a evitar';return}if(!await loadChart())return;const o=await call('overlay',{depth:depth()});if(!o||!o.pixels)return;const cv=document.createElement('canvas');cv.width=o.width;cv.height=o.height;cv.getContext('2d').putImageData(new ImageData(o.pixels,o.width,o.height),0,0);shade=L.imageOverlay(cv.toDataURL(),o.bounds,{opacity:1,interactive:false}).addTo(map);el('routeShade').textContent='Ocultar áreas a evitar'}

for(const [id,type] of [['routeStart','start'],['routeEnd','end'],['routeVia','via']])el(id).onclick=()=>select(type);
map.on('click',e=>{if(!mode)return;const p={lat:e.latlng.lat,lng:e.latlng.lng};if(mode==='via'){if(route.via.length>=50)return;route.via.splice(bestSlot(p),0,p)}else route[mode]=p;save();select(null)});
el('routeMargin').onchange=()=>{savePrefs();schedule()};
el('routeDepth').onchange=async()=>{savePrefs();schedule();if(shade){shade.remove();shade=null;await toggleShade()}};
el('routeShade').onclick=toggleShade;
el('routeClear').onclick=()=>{if(!route.start&&!route.end&&!route.via.length)return;if(!confirm('Apagar o roteiro salvo neste aparelho?'))return;route={start:null,end:null,via:[]};save();select(null)};
el('routeExport').onclick=()=>{if(!computed){info('Calcule uma rota (origem e destino) antes de exportar.',true);return}const first=computed.access[0],last=computed.access[computed.access.length-1],pts=[...(first?first.coords.slice(0,-1):[]),...computed.coords,...(last?last.coords.slice(1):[])];const xml=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="ParatyGPS" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>Rota sugerida ParatyGPS — conferir na carta</name><desc>Calculada sobre a carta DHN 1633: evita terra, secos e profundidades menores que ${computed.depth} m (reduzidas à baixa-mar média de sizígia) com margem de ${computed.margin} m. Não substitui a carta atualizada, avisos aos navegantes e a vigilância a bordo.</desc></metadata><rte><name>Rota sugerida — Paraty</name>${pts.map((p,i)=>`<rtept lat="${p[0].toFixed(6)}" lon="${p[1].toFixed(6)}"><name>${i===0?'Origem':i===pts.length-1?'Destino':'R'+String(i).padStart(2,'0')}</name></rtept>`).join('')}</rte></gpx>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([xml],{type:'application/gpx+xml'}));a.download='paraty-rota-sugerida.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
render();if(route.start&&route.end)schedule();else info('Marque origem e destino no mapa para calcular a rota.');
})();
