(()=>{'use strict';
const map=window.paratyMap, L=window.L;
if(!map||!L)return;
const el=id=>document.getElementById(id), key=window.paratyStorageKey('paratygps-route-v1');
let route={start:null,end:null,via:[]},mode=null,drawn=[],line=null;
try{const value=JSON.parse(localStorage.getItem(key));if(value&&typeof value==='object')route={start:valid(value.start),end:valid(value.end),via:Array.isArray(value.via)?value.via.map(valid).filter(Boolean).slice(0,50):[]}}catch{}
function valid(p){return p&&Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&Math.abs(p.lat)<=90&&Math.abs(p.lng)<=180?{lat:p.lat,lng:p.lng}:null}
const format=p=>`${Math.abs(p.lat).toFixed(5)}° ${p.lat<0?'S':'N'} · ${Math.abs(p.lng).toFixed(5)}° ${p.lng<0?'O':'L'}`;
function nauticalMiles(a,b){const r=Math.PI/180,dLat=(b.lat-a.lat)*r,dLon=(b.lng-a.lng)*r,v=Math.sin(dLat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dLon/2)**2;return 3440.065*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))}
function save(){localStorage.setItem(key,JSON.stringify(route));render()}
function select(next){mode=mode===next?null:next;window.routeSelectionActive=Boolean(mode);for(const [id,type] of [['routeStart','start'],['routeEnd','end'],['routeVia','via']]){el(id).classList.toggle('selected',mode===type);el(id).setAttribute('aria-pressed',String(mode===type))}document.querySelector('.maptop span').textContent=mode?`Toque no mapa para ${mode==='via'?'inserir passagem':mode==='start'?'marcar origem':'marcar destino'}`:'Toque no mapa para selecionar um ponto'}
function icon(label,via){return L.divIcon({className:'',html:`<div class="route-point ${via?'route-via':''}" style="width:28px;height:28px">${label}</div>`,iconSize:[28,28],iconAnchor:[14,14]})}
function render(){drawn.forEach(m=>m.remove());drawn=[];if(line){line.remove();line=null}const list=el('routeList');list.replaceChildren();const entries=[['Origem',route.start,'start',0],...route.via.map((p,i)=>[`Passagem ${i+1}`,p,'via',i]),['Destino',route.end,'end',0]];
for(const [name,p,type,index] of entries){const row=document.createElement('div');row.className='route-item';const label=document.createElement('span');label.innerHTML=`<strong>${name}</strong><small>${p?format(p):'Ainda não definido'}</small>`;row.append(label);if(p){const btn=document.createElement('button');btn.className='iconbtn';btn.textContent='×';btn.setAttribute('aria-label',`Remover ${name}`);btn.onclick=()=>{if(type==='via')route.via.splice(index,1);else route[type]=null;save()};row.append(btn);const marker=L.marker([p.lat,p.lng],{icon:icon(type==='start'?'A':type==='end'?'B':String(index+1),type==='via'),draggable:true,zIndexOffset:600}).addTo(map).bindPopup(`${name}<br>${format(p)}<br>Arraste para ajustar`);marker.on('dragend',()=>{const point=marker.getLatLng(),value={lat:point.lat,lng:point.lng};if(type==='via')route.via[index]=value;else route[type]=value;save()});drawn.push(marker)}list.append(row)}
// A direct A–B segment is intentionally never drawn. Intermediate legs are only a planning sketch.
const points=[route.start,...route.via,route.end].filter(Boolean);if(route.start&&route.end&&route.via.length){line=L.polyline(points.map(p=>[p.lat,p.lng]),{color:'#e58b3b',weight:3,dashArray:'7 9',opacity:.9,interactive:false}).addTo(map)}
let nm=0;if(route.start&&route.end&&route.via.length)for(let i=1;i<points.length;i++)nm+=nauticalMiles(points[i-1],points[i]);el('routeDistance').textContent=nm?`Distância do rascunho: ${nm.toFixed(2).replace('.',',')} MN · trechos não verificados`:'Adicione ao menos uma passagem para visualizar o rascunho. Nenhuma rota segura é calculada.'}
for(const [id,type] of [['routeStart','start'],['routeEnd','end'],['routeVia','via']])el(id).onclick=()=>select(type);
map.on('click',e=>{if(!mode)return;const p={lat:e.latlng.lat,lng:e.latlng.lng};if(mode==='via'){if(route.via.length>=50)return;route.via.push(p)}else route[mode]=p;save();select(null)});
el('routeClear').onclick=()=>{if(!route.start&&!route.end&&!route.via.length)return;if(!confirm('Apagar o rascunho de roteiro salvo neste aparelho?'))return;route={start:null,end:null,via:[]};save();select(null)};
el('routeExport').onclick=()=>{if(!route.start||!route.end||!route.via.length){el('routeDistance').textContent='Defina origem, destino e ao menos uma passagem antes de exportar.';return}const points=[route.start,...route.via,route.end];const xml=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="ParatyGPS" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>RASCUNHO NÃO VALIDADO — NÃO NAVEGAR</name><desc>Trechos não verificados quanto a terra, profundidade, lajes, maré ou calado.</desc></metadata><rte><name>RASCUNHO NÃO VALIDADO — Paraty</name>${points.map((p,i)=>`<rtept lat="${p.lat}" lon="${p.lng}"><name>${i===0?'Origem':i===points.length-1?'Destino':'Passagem '+i}</name></rtept>`).join('')}</rte></gpx>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([xml],{type:'application/gpx+xml'}));a.download='paraty-rascunho-nao-validado.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
render();
})();
