const CACHE='paratygps-shell-v8',TILES='paratygps-tiles-v1',TILE_HOSTS=['tile.openstreetmap.org','tiles.openseamap.org'],MAX_TILES=4000,REFRESH_MS=14*864e5;const SHELL=['./','./index.html','./leaflet.css','./leaflet.js','./route.js','./history.js','./manifest.webmanifest','./icon-192.png','./icon-512.png'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE&&k!==TILES).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
// Map tiles already viewed are kept on the device so the chart still shows at sea without signal.
// Only CORS responses are stored: opaque ones would count several MB each against the storage quota.
const noCors=new Set();let puts=0;
async function trim(){const c=await caches.open(TILES),keys=await c.keys();for(let i=0;i<keys.length-MAX_TILES;i++)await c.delete(keys[i])}
async function fetchTile(req){const url=new URL(req.url);if(!noCors.has(url.host)){try{const res=await fetch(req.url,{mode:'cors',credentials:'omit'});if(res.ok){const body=await res.blob();const stored=new Response(body,{headers:{'content-type':res.headers.get('content-type')||'image/png','x-cached-at':String(Date.now())}});const c=await caches.open(TILES);await c.delete(req.url);await c.put(req.url,stored.clone());if(++puts%50===0)trim();return stored}return res}catch{const res=await fetch(req);noCors.add(url.host);return res}}return fetch(req)}
async function tile(e){const cached=await caches.match(e.request.url,{cacheName:TILES});if(cached){if(navigator.onLine&&Date.now()-Number(cached.headers.get('x-cached-at')||0)>REFRESH_MS)e.waitUntil(fetchTile(e.request).catch(()=>{}));return cached}try{return await fetchTile(e.request)}catch{return Response.error()}}
self.addEventListener('message',e=>{if(e.data==='tile-count')e.waitUntil(caches.open(TILES).then(c=>c.keys()).then(k=>e.source&&e.source.postMessage({type:'tile-count',count:k.length})))});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(TILE_HOSTS.includes(u.host)){e.respondWith(tile(e));return}if(u.origin!==self.location.origin)return;if(e.request.mode==='navigate'){e.respondWith(fetch(e.request).catch(()=>caches.match('./index.html')));return}e.respondWith(caches.match(e.request).then(v=>v||fetch(e.request)))});
